apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: game
  name: game
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 3
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - image: kiran2361993/kubegame:v2
          name: kubegame